# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sawtooth_identity/protobuf/identities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sawtooth_identity/protobuf/identities.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n+sawtooth_identity/protobuf/identities.proto\"\x8b\x01\n\x0fIdentityPayload\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.IdentityPayload.IdentityType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"=\n\x0cIdentityType\x12\x17\n\x13IDENTITY_TYPE_UNSET\x10\x00\x12\n\n\x06POLICY\x10\x01\x12\x08\n\x04ROLE\x10\x02\x42\x1e\n\x1asawtooth.identity.protobufP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_IDENTITYPAYLOAD_IDENTITYTYPE = _descriptor.EnumDescriptor(
  name='IdentityType',
  full_name='IdentityPayload.IdentityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDENTITY_TYPE_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLICY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=126,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_IDENTITYPAYLOAD_IDENTITYTYPE)


_IDENTITYPAYLOAD = _descriptor.Descriptor(
  name='IdentityPayload',
  full_name='IdentityPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='IdentityPayload.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='IdentityPayload.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IDENTITYPAYLOAD_IDENTITYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=187,
)

_IDENTITYPAYLOAD.fields_by_name['type'].enum_type = _IDENTITYPAYLOAD_IDENTITYTYPE
_IDENTITYPAYLOAD_IDENTITYTYPE.containing_type = _IDENTITYPAYLOAD
DESCRIPTOR.message_types_by_name['IdentityPayload'] = _IDENTITYPAYLOAD

IdentityPayload = _reflection.GeneratedProtocolMessageType('IdentityPayload', (_message.Message,), dict(
  DESCRIPTOR = _IDENTITYPAYLOAD,
  __module__ = 'sawtooth_identity.protobuf.identities_pb2'
  # @@protoc_insertion_point(class_scope:IdentityPayload)
  ))
_sym_db.RegisterMessage(IdentityPayload)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032sawtooth.identity.protobufP\001'))
# @@protoc_insertion_point(module_scope)
